INSERT INTO songs (Song_name, artist, genre)
VALUES ('Blinding Lights', 'The Weeknd', 'Synthwave'), 
('The Twist', 'Chubby Checker', 'Rock'), 
('Smooth', 'Santana', 'Rock'), 
('Mack The Knife', 'Bobby Darin', 'Jazz'), 
('Uptown Funk!', 'Mark Ronson', 'Funk'), 
('How Do I Live', 'LeAnn Rimes', 'Country'), 
('Party Rock Anthem', 'LMFAO', 'House'), 
('I Gotta Feeling', 'The Black Eyed Peas', 'House'), 
('Macarena', 'Los Del Rio', 'Flamenco'), 
('Shape Of You', 'Ed Sheeran', 'Pop'), 
('Physical', 'Olivia Newton-John', 'Dance'), 
('You Light Up My Life', 'Debby Boone', 'Rock'), 
('Hey Jude', 'The Beatles', 'Rock'), 
('Closer', 'The Chainsmokers', 'EDM'), 
('We Belong Together', 'Mariah Carey', 'R&B'), 
('Un-Break My Heart', 'Toni Braxton', 'R&B'), 
('Yeah!', 'Usher', 'Crunk'), 
('Bette Davis Eyes', 'Kim Carnes', 'Crunk'), 
('Circles', 'Post Malone', 'Rock'), 
('Endless Love', 'Lionel Richie', 'Ballad'), 
('Tonight''s The Night', 'Rob Stewart', 'Rock'), 
('Foolish Games', 'Jewel', 'Rock'), 
('I Do It For You', 'Bryan Adams', 'Rock'), 
('I''ll Make Love To You', 'Boyz II Men', 'R&B'), 
('The Theme From A Summer Place', 'Percy Faith And His Orchestra', 'Pop'), 
('Le Freak', 'Chic', 'Disco'), 
('How Deep Is Your Love', 'Bee Gees', 'Rock'), 
('Eye Of The Tiger', 'Survivor', 'Rock'), 
('We Found Love', 'Rihanna', 'Electro'), 
('Girls Like You', 'Marron 5', 'Pop'), 
('Girls Like You', 'Marron 5', 'Pop'), 
('Low', 'Flo Rida', 'Hip Hop'), 
('Levitating', 'Dua Lipa', 'Disco'), 
('I Just Want To Be Your Everything', 'Andy Gibb', 'Pop'), 
('Too Close', 'Next', 'R&B'), 
('Every Breath You Take', 'The Police', 'Rock'), 
('Somebody That I Used To Know', 'Gotye', 'Pop'), 
('Despacito', 'Luis Fonsi', 'Reggaeton'), 
('Flashdance... What A Feeling', 'Irene Cara', 'Rock'), 
('Rolling In The Deep', 'Adele', 'Blues'), 
('Old Town Road', 'Lil Nas X', 'Country'), 
('The Battle Of New Orleans', 'Johnny Horton', 'Novelty March'), 
('One Sweet Day', 'Mariah Carey', 'Ballad'), 
('Truly Madly Deeply', 'Savage Garden', 'Pop'), 
('Silly Love songs', 'Wings', 'Disco'), 
('Let''s Get It On', 'Marvin Gaye', 'Funk'), 
('Another One Bites The Dust', 'Queen', 'Rock'), 
('Mood', '24kGoldn', 'Rap'), 
('Say Say Say', 'Paul McCartney', 'Pop'), 
('How You Remind Me', 'Nickleback', 'Grunge'), 
('Tie A Yellow Ribbon Round The Ole Oak Tree', 'Dawn', 'Pop'), 
('It''s All In The Game', 'Tommy Edwards', 'Soul'), 
('I Want To Hold Your Hand', 'The Beatles', 'Rock'), 
('Shadow Dancing', 'Andy Gibb', 'Disco'), 
('Call Me Maybe', 'Carly Rae Jepsen', 'Pop'), 
('Blurred Lines', 'Robin Thicke', 'R&B'), 
('Something About The Way You Look Tonight', 'Elton John', 'Pop'), 
('No One', 'Alicia Keys', 'R&B'), 
('I Will Always Love You', 'Whitney Houston', 'Soul'), 
('End Of The Road', 'Boyz II Men', 'R&B'), 
('Perfect', 'Ed Sheeran', 'Pop'), 
('Boom Boom Pow', 'The Black Eyed Peas', 'EDM'), 
('Call Me', 'Blondie', 'Rock'), 
('Let Me Love You', 'Mario', 'House'), 
('Stayin'' Alive', 'Be Gees', 'Disco'), 
('Lady', 'Kenny Rogers', 'Country'), 
('Tik Tok', 'Ke$ha', 'Dance'), 
('I''m A Believer', 'The Monkees', 'Rock'), 
('Gold Digger', 'Kanye West', 'Hip Hop'), 
('Apologize', 'Timbaland', 'R&B'), 
('The Sign', 'Ace Of Base', 'Techno'), 
('Centerfold', 'The J. Geils Band', 'Rock'), 
('All About That Bass', 'Meghan Trainor', 'Rock'), 
('Sunflower', 'Swae Lee', 'Hip Hop'), 
('Starting Over', 'John Lennon', 'Rock'), 
('Royals', 'Lorde', 'Pop'), 
('The Boy Is Mine', 'Brandy & Monica', 'R&B'), 
('Because I Love You', 'Stevie B', 'Pop'), 
('I Love Rock ''N Roll', 'Joan Jett & The Blackhearts', 'Rock'), 
('Let The Sunshine In', 'The 5th Dimension', 'Pop'), 
('Whoomp!', 'Tag Team', 'Hip Hop'), 
('God''s Plan', 'Drake', 'Pop'), 
('Moves Like Jagger', 'Maroon 5', 'Electro'), 
('Ebony And Ivory', 'Paul McCartney', 'Rock'), 
('Rush Rush', 'Paula Abdul', 'Rock'), 
('That''s What Friends Are For', 'Dionne & Friends', 'Pop'), 
('Happy', 'Pharrell Williams', 'Pop'), 
('Upside Down', 'Diana Ross', 'Soul'), 
('Sugar, Sugar', 'The Archies', 'Rock'), 
('Just The Way You Are', 'Bruno Mars', 'Pop'), 
('Dilemma', 'Nelly', 'Hip Hop'), 
('I Heard It Through The Grapevine', 'Marvin Gaye', 'Soul'), 
('You''re Still The One', 'Shania Twain', 'Country'), 
('Billie Jean', 'Michael Jackson', 'Pop'), 
('Hot Stuff', 'Donna Summer', 'Rock'), 
('Rockstar', 'Post Malone', 'Hip Hop'), 
('Gangsta''s Paradise', 'Coolio', 'Hip Hop'), 
('Abracadabra', 'The Steve Miller Band', 'Rock'), 
('You''re So Vain', 'Carly Simon', 'Rock'), 
('Not Like Us','Kendrick Lamar', 'Hip Hop');